name: gitwhisper
description: AI-powered Git commit message generator that whispers the perfect commit message for your changes
version: 0.0.58
repository: https://github.com/iamngoni/gitwhisper
homepage: https://github.com/iamngoni/gitwhisper

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.6.0
  cli_completion: ^0.5.1
  dio: ^5.8.0+1
  mason_logger: ^0.3.2
  path: ^1.9.1
  pub_updater: ^0.5.0
  universal_io: ^2.2.2
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0

executables:
  gitwhisper: main
  gw: main
