name: Build Binaries

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get

      - name: Compile binary
        run: |
          dart compile exe bin/gitwhisper.dart -o gitwhisper${{ runner.os == 'Windows' && '.exe' || '' }}

      - name: Archive binary
        run: |
          tar -czf gitwhisper-${{ runner.os }}.tar.gz gitwhisper${{ runner.os == 'Windows' && '.exe' || '' }}

      - uses: actions/upload-artifact@v4
        with:
          name: gitwhisper-${{ matrix.os }}
          path: gitwhisper-*.tar.gz
