name: gitwhisper

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/gitwhisper.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/gitwhisper.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart format --set-exit-if-changed .
      - run: dart analyze
      - run: dart test

  verify-version:
    runs-on: self-hosted
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v2

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: 📦 Install Dependencies
        run: |
          dart pub get

      - name: 🔎 Verify version
        run: dart run test --run-skipped -t version-verify
